/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_ids_clientes.h"

retorno *
obtener_nuevo_id_cliente_1_svc(void *argp, struct svc_req *rqstp)
{
	static retorno  result;

	/*
	 * insert server code here
	 */

	return &result;
}
