/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDOR_IDS_CLIENTES_H_RPCGEN
#define _SERVIDOR_IDS_CLIENTES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct retorno {
	int cod_ret;
	union {
		char id_cliente[800];
		char msj_error[800];
	} retorno_u;
};
typedef struct retorno retorno;

#define SERVIDOR_IDS_PROG 0x20000099
#define SERVIDOR_IDS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTENER_NUEVO_ID_CLIENTE 1
extern  retorno * obtener_nuevo_id_cliente_1(void *, CLIENT *);
extern  retorno * obtener_nuevo_id_cliente_1_svc(void *, struct svc_req *);
extern int servidor_ids_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTENER_NUEVO_ID_CLIENTE 1
extern  retorno * obtener_nuevo_id_cliente_1();
extern  retorno * obtener_nuevo_id_cliente_1_svc();
extern int servidor_ids_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDOR_IDS_CLIENTES_H_RPCGEN */
