/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_ids_clientes.h"
#include "ServidorIds.h"

retorno * obtener_nuevo_id_cliente_1_svc(void *argp, struct svc_req *rqstp){
	static retorno result;
	result.cod_ret = 1;
	result.retorno_u.id_cliente = 0;
	ServidorIds servidorIds;
	ServidorIds_Conectar( &servidorIds );
	int idCliente = ServidorIds_PedirId( &servidorIds );
	printf("Se quiere entregar el id %i\n", idCliente);
	if( !servidorIds.huboError ){
		result.cod_ret = 1;
		result.retorno_u.id_cliente = idCliente;
		printf("Todod joya %i\n", idCliente);
	}else{
		result.cod_ret = 2;
		strcpy(result.retorno_u.msj_error, servidorIds.msjError);
		printf("Errorrr %s\n", servidorIds.msjError);
	}
	ServidorIds_Desconectar( &servidorIds );
	return &result;
}

retorno * devolver_id_cliente_1_svc(int *id, struct svc_req *rqstp){
	static retorno result;

	printf("Se quiere devolver el id %i\n", *id);
	ServidorIds servidorIds;
	ServidorIds_Conectar( &servidorIds );
	ServidorIds_DevolverId( &servidorIds, *id );
	if( !servidorIds.huboError ){
		result.cod_ret = 1;
		result.retorno_u.id_cliente = *id;
	}else{	
		result.cod_ret = 2;
		strcpy(result.retorno_u.msj_error, servidorIds.msjError);
	}
	ServidorIds_Desconectar( &servidorIds );
	return &result;
}
