/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_ids_clientes.h"
#include "ServidorIds.h"

retorno * obtener_nuevo_id_cliente_1_svc(void *argp, struct svc_req *rqstp){
	static retorno result;
	ServidorIds servidorIds;
	int idCliente = servidorIds.pedirId();
	result.cod_ret = 1;
	sprintf( result.retorno_u.id_cliente, "%d", idCliente );
	return &result;
}
