/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "servidor_ids_clientes.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

retorno *
obtener_nuevo_id_cliente_1(void *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENER_NUEVO_ID_CLIENTE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
