/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_ids_clientes.h"


void
servidor_ids_prog_1(char *host)
{
	CLIENT *clnt;
	retorno  *result_1;
	char *obtener_nuevo_id_cliente_1_arg;
	retorno  *result_2;
	int  devolver_id_cliente_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDOR_IDS_PROG, SERVIDOR_IDS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = obtener_nuevo_id_cliente_1((void*)&obtener_nuevo_id_cliente_1_arg, clnt);
	if (result_1 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(result_1->cod_ret == 1)
		printf( "Se pide el Id. cod_ret: %d, id_cliente: %i\n", result_1->cod_ret, result_1->retorno_u.id_cliente );
	else
		printf( "Se pide el Id. cod_ret: %d, error: %s\n", result_1->cod_ret, result_1->retorno_u.msj_error );
	devolver_id_cliente_1_arg = result_1->retorno_u.id_cliente;
	result_2 = devolver_id_cliente_1(&devolver_id_cliente_1_arg, clnt);
	if (result_2 == (retorno *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(result_2->cod_ret == 1)
		printf( "Se devuelve el Id. cod_ret: %d, id_cliente: %i\n", result_2->cod_ret, result_2->retorno_u.id_cliente );
	else
		printf( "Se pide el Id. cod_ret: %d, error: %s\n", result_2->cod_ret, result_2->retorno_u.msj_error );


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidor_ids_prog_1 (host);
exit (0);
}
